### ISSUE TITLE
Production Build of CSS is not possible

### ISSUE THREAD

**Issue by rokde** [inertiajs/pingcrm#42]
Tailwind: ^0.7.4 or ^1.0 (issue is the same)
yarn: 1.15.2

Calling `yarn run dev` or `yarn run watch` compiles without any error.

Calling `yarn run prod` or `yarn run production` shows error like this:

```bash
CssSyntaxError: /css/app.css:64052:3: Unknown word
    at Input.error (/var/www/html/node_modules/postcss/lib/input.js:130:16)
    at Parser.unknownWord (/var/www/html/node_modules/postcss/lib/parser.js:563:22)
    at Parser.decl (/var/www/html/node_modules/postcss/lib/parser.js:235:16)
    at Parser.other (/var/www/html/node_modules/postcss/lib/parser.js:166:12)
    at Parser.parse (/var/www/html/node_modules/postcss/lib/parser.js:77:16)
    at parse (/var/www/html/node_modules/postcss/lib/parse.js:17:12)
    at new LazyResult (/var/www/html/node_modules/postcss/lib/lazy-result.js:60:16)
    at Processor.<anonymous> (/var/www/html/node_modules/postcss/lib/processor.js:138:12)
    at Processor.process (/var/www/html/node_modules/postcss/lib/processor.js:117:23)
    at Function.creator.process (/var/www/html/node_modules/postcss/lib/postcss.js:148:43)
    at OptimizeCssAssetsWebpackPlugin.processCss (/var/www/html/node_modules/optimize-css-assets-webpack-plugin/src/index.js:73:21)
    at Object.processor (/var/www/html/node_modules/optimize-css-assets-webpack-plugin/src/index.js:13:18)
    at /var/www/html/node_modules/last-call-webpack-plugin/src/index.js:150:10
    at arrayEach (/var/www/html/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/var/www/html/node_modules/lodash/forEach.js:38:10)
    at OptimizeCssAssetsWebpackPlugin.process (/var/www/html/node_modules/last-call-webpack-plugin/src/index.js:147:5)
    at /var/www/html/node_modules/last-call-webpack-plugin/src/index.js:178:28
    at _next0 (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:17)
    at eval (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /var/www/html/node_modules/terser-webpack-plugin/dist/index.js:321:9
    at step (/var/www/html/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:9)
    at done (/var/www/html/node_modules/terser-webpack-plugin/dist/TaskRunner.js:98:30)
    at tryCatcher (/var/www/html/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/html/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/var/www/html/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/var/www/html/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/var/www/html/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/var/www/html/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/www/html/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/www/html/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/var/www/html/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
```

Can anybody help?

**Comment by Juhlinus** [comment]
Hello @rokde !

Which version of PingCRM are you running? Make sure that you're on the latest commit, which would be commit 99c7172.

I normally don't use `yarn`, but I can run `yarn run prod` fine on a fresh PingCRM clone.

My yarn version seems to differ from yours as well. Would you mind making sure that yarn is on the latest version?

Also, try cloning a fresh copy of PingCRM to see if you can do `yarn run prod` on that.

```
➜  pingcrm git:(master) ✗ yarn run prod
yarn run v1.17.3
$ npm run production
npm WARN lifecycle The node binary used for scripts is /var/folders/0j/kktyx_295w17hhz8p66yvyzw0000gn/T/yarn--1566247745389-0.3669908788458742/node but npm is using /usr/local/Cellar/node/12.6.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @ production /Users/linusjuhlin/Projects/pingcrm
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js



 DONE  Compiled successfully in 25200ms                                                                                                                                                                                          10:49:32 PM

                               Asset      Size  Chunks                    Chunk Names
                        /css/app.css  1.46 MiB      15  [emitted]  [big]  /js/app
                          /js/app.js   104 KiB      15  [emitted]         /js/app
                      /js/app.js.map   496 KiB      15  [emitted]         /js/app
 js/0.js.map?id=843fcaa14d96386d12f6   124 KiB       0  [emitted]         
     js/0.js?id=843fcaa14d96386d12f6  21.1 KiB       0  [emitted]         
 js/1.js.map?id=9effa05dd31869e1c2ff  54.2 KiB       1  [emitted]         
     js/1.js?id=9effa05dd31869e1c2ff  18.2 KiB       1  [emitted]         
js/10.js.map?id=0978f69ffe725dfd0230  17.9 KiB      10  [emitted]         
    js/10.js?id=0978f69ffe725dfd0230  5.71 KiB      10  [emitted]         
js/11.js.map?id=fc1f9c5a2eedd3880ed6    21 KiB      11  [emitted]         
    js/11.js?id=fc1f9c5a2eedd3880ed6  6.74 KiB      11  [emitted]         
js/12.js.map?id=49fd7383467f11b1afee  15.7 KiB      12  [emitted]         
    js/12.js?id=49fd7383467f11b1afee  4.84 KiB      12  [emitted]         
js/13.js.map?id=0ad7c4aeefb30c841c2f  12.7 KiB      13  [emitted]         
    js/13.js?id=0ad7c4aeefb30c841c2f  4.11 KiB      13  [emitted]         
js/14.js.map?id=9322b6611013f86a9d74  10.5 KiB      14  [emitted]         
    js/14.js?id=9322b6611013f86a9d74   3.4 KiB      14  [emitted]         
 js/2.js.map?id=593e17f1ecc158c875e3   672 KiB       2  [emitted]  [big]  
     js/2.js?id=593e17f1ecc158c875e3  69.3 KiB       2  [emitted]         
 js/3.js.map?id=5d5f9d50de15a154dbf0  65.6 KiB       3  [emitted]         
     js/3.js?id=5d5f9d50de15a154dbf0    22 KiB       3  [emitted]         
 js/4.js.map?id=450d54043a99f00cc830  64.1 KiB       4  [emitted]         
     js/4.js?id=450d54043a99f00cc830  21.6 KiB       4  [emitted]         
 js/5.js.map?id=842acc78e7b41a1cff7c  62.4 KiB       5  [emitted]         
     js/5.js?id=842acc78e7b41a1cff7c  21.4 KiB       5  [emitted]         
 js/6.js.map?id=10325c5f38e02b84d2ef  22.1 KiB       6  [emitted]         
     js/6.js?id=10325c5f38e02b84d2ef  7.54 KiB       6  [emitted]         
 js/7.js.map?id=1df230105d376bb18133  47.1 KiB       7  [emitted]         
     js/7.js?id=1df230105d376bb18133  16.5 KiB       7  [emitted]         
 js/8.js.map?id=032b645634c4e254c98e  45.8 KiB       8  [emitted]         
     js/8.js?id=032b645634c4e254c98e  16.1 KiB       8  [emitted]         
 js/9.js.map?id=63377e91e6a6f88c8729  21.5 KiB       9  [emitted]         
     js/9.js?id=63377e91e6a6f88c8729  6.58 KiB       9  [emitted]         
✨  Done in 29.39s.
➜  pingcrm git:(master) ✗
```

**Comment by rokde** [comment]
Hi @Juhlinus ,

I have the problems with the content of the HEAD of master and with content of the #24 .

And I have the same error no matter using npm or yarn.

**Comment by Juhlinus** [comment]
Could you try it with a fresh clone of the repository and see if the issue persists?

**Comment by jetwes** [comment]
I tried it with #24 - worked without any problems. Only concern is that the generated app.css is about 700kb large

**Comment by rokde** [comment]
You are right, the source builds production files. Sorry for opening the issue. I am looking forward to my changes which leads to the error.
